### ISSUE TITLE
Only ECDSA keys supported

### ISSUE THREAD

**Issue by hjames9** [pion/dtls#133]
Hello, it appears in the code that only ECDSA keys are supported.
https://github.com/pion/dtls/blob/master/conn.go#L100

However in the documentation (mainly README.md), it mentions the following ciper suites as being supported:
TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA

Is the documentation incorrect or is there another way to bypass that certificate type check?

**Comment by Sean-Der** [comment]
@hjames9 I *believe* RSA works if the remote offers it, but you are right locally we only support ECDSA.

I am not against supporting it though, just need to see the complexity vs value trade off. I don't want to add bugs for other things in the process of supporting it.

**Comment by rumpelsepp** [comment]
Is adding support for (local) ed25519 keys possible in the current codebase? I mean, are there only  a few lines that need to be changed, or is some larger refactoring needed?

**Comment by Sean-Der** [comment]
@rumpelsepp I *think* just a few lines need changing. 

We have a few cases where we switch off the type of the key. Someone just needs to support the cases where that fails and we should be good!

**Comment by rumpelsepp** [comment]
ed25519 is implemented as of today.

**Comment by hjames9** [comment]
@Sean-Der I was thinking of maybe tackling RSA certificate support.   Is there anything in particular you were weary about with this implementation?

**Comment by Sean-Der** [comment]
@hjames9 if you copy/change what @rumpelsepp did it should be perfect!

So excited you are contributing, are you interested in being involved long term? I can add you to the Pion organization, then you can merge your own PRs after one approval (and you can approve others!)

Also if you want quicker responses I am on [slack](pion.ly/slack) 24/7 :)

**Comment by hjames9** [comment]
@Sean-Der Great!  I'll submit a PR adding RSA support modeling what @rumpelsepp has done, which can be used to close out this ticket.

Would love to join Pion, and I will also hop on Slack.  Thanks!

**Comment by rumpelsepp** [comment]
I think rsa is not that easy as ed25519, since there are multiple signature formats available and these need to be marshalled with asn1. I need to read the rfc though…

**Comment by daenney** [comment]
I'm going to close this issue. If people want to support additional key types then PRs are always welcome. If people want to submit a PR to clarify that we only support the RSA in certain situations, that's also fine and appreciated.

**Comment by GregorioDiStefano** [comment]
Reopening this instead of creating a new issue.

I noticed that when testing a webrtc implementation, pion DTLS ends up using `TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256` (first matching ciphersuite that matches server), but, since pion only generates a ECDSA signed certificate, the server ends up sending `ILLEGAL PARAMETER` and the handshake fails. 

this clearly seems like a bug, and I believe instead of creating just a ECDSA certificate in dtlstransport.go here: https://github.com/pion/webrtc/blob/master/dtlstransport.go#L73, we should in addition also generate an RSA signed one, in case it will be used after we've negotiated an RSA client certificate. Does that make sense? I'd like to make an attempt at fixing this, so any input would be helpful.

**Comment by PieerePi** [comment]
@GregorioDiStefano I had the same problem when I tested FreeSWITCH with pion. I‘ve modified some code in my repository and want to PR it to pion/dtls. Do you have time to have a check and see if they are consistent with what you said? Thanks!

https://github.com/PieerePi/dtls/commit/64dd74edb5e2216f0d7bfc4f943e8e794f29d1e2
