### ISSUE TITLE
How to be notified when *dtls.Conn is closed/Connection state

### ISSUE THREAD

**Issue by Sean-Der** [pion/dtls#151]
This is open for discussion, but in `pion/dtls` I want to be notified when the DTLS Conn is closed. The read is happening on the other side of the code base, so the return value isn't really useful. It also doesn't feel right to me to call `Read()` and possibly have it hang if I just want to get the current state.

I don't have anyone reading/writing from the DTLS connection, but eventually I will get an encrypted alert for closing. I haven't found any patterns in `crypto/tls` or any stdlib packages that pop out at me.

**Comment by daenney** [comment]
The problem I see with this is that we can never reliably know if a connection is closed, since there is no connection. We're just screaming into the void hoping someone is listening on the other side. If I look at the RFC there's also nothing in there about detecting this, since it's not any different from a generic network failure from the DTLS point of view . We'd need a mechanism at the application level that both sender and receiver agree to use in order to signal the end of a transaction between them, best I can tell.

I suspect the reason why you're not seeing any of it in `crypto/tls` is b/c in that case it'll piggy-back on the connection signalling of TCP.

**Comment by rumpelsepp** [comment]
Isn't there heartbeat specified for DTLS for these kind of issues?
https://tools.ietf.org/html/rfc6520

**Comment by daenney** [comment]
I hadn't seen that before! It turns out we made a decision before in #15 to not implement this though. It appears to have some security implications, being at the core of Heartbleed.

**Comment by rumpelsepp** [comment]
> some security implications

what are these exactly? heartbleed was an implementation mistake. the RFC states:

> This document does not introduce any new security considerations.

**Comment by daenney** [comment]
Heartbleed was an implementation mistake on the heartbeat mechanism. As pointed out in #15, at least LibreSSL pulled support for the mechanism entirely over it.

**Comment by rumpelsepp** [comment]
> Heartbleed was an implementation mistake on the heartbeat mechanism.

That's the point. The concept of keepalives is fine. For DTLS stuff it even makes a lot of sense. The OpenBSD folks striped it out, since they want to reduce code complexity. 

IIRC gnutls supports it.

**Comment by Sean-Der** [comment]
I just need a `OnClose` or some sort of status callback. DTLS already closes for me (I have a reliable connection over WebRTC) and a loss of connection is handled by ICE.

When the other side closes we get an encrypted alert, and it properly shuts everything down.

We can add the heartbeats though! I am not against it, just doesn't provide any value for me for the issue I am trying to solve currently.

**Comment by rumpelsepp** [comment]
Ah. I see. I figure, we are on our own here. One idea though might be looking at the go-quic implementation. They might come into simalar problems.

https://github.com/lucas-clemente/quic-go

**Comment by Sean-Der** [comment]
@rumpelsepp what do you think of doing something like `RequestWithContext` ? https://golang.org/pkg/net/http/#NewRequestWithContext

**Comment by Sean-Der** [comment]
IMO we should make it the default also, and `Server` and `Client` should both take it as an argument.

**Comment by rumpelsepp** [comment]
IIRC context helps you to signal spawned children (goroutines) all at once from the caller (aka tree root). It is not possible to propagate the information the tree up to that caller. How does this help if the error happens deep in the calling stack?

**Comment by Sean-Der** [comment]
Closing for #189

**Comment by audiolion** [comment]
Discussed with @Sean-Der today in Pion Slack and this was not actually solved by #189 . Reopening issue.

If we add a Close handler we can let `pion/webrtc` know about the connection closing so graceful teardown happens immediately instead of after the timeout. While this won't work for all cases -- because not all webrtc implementations will be good citizens and send RTCP BYE when the connection is closed -- we can at least make the happy path a bit better.
