### ISSUE TITLE
community

### ISSUE THREAD

**Issue by backkem** [pion/dtls#35]
This ticket is used to track and reach out to related projects.

- [thomas-fossati/dtls](https://github.com/thomas-fossati/dtls)

Please prefer using the [Golang Slack](https://invite.slack.golangbridge.org/) [#pion](http://gophers.slack.com/messages/pion) channel or [mailing list](https://groups.google.com/forum/#!forum/pion) for long form discussions.

**Comment by backkem** [comment]
@thomas-fossati let us know if you're interested in up-streaming your work. We're always looking to accommodate related efforts.

**Comment by thomas-fossati** [comment]
Hi Michiel,

Sure, it'd be great, two things though:
- There is a dependency on the upstream spec which we expect (finger crossed) to finalise in the next IETF cycle (between March and July);
- This specific feature impacts Pions' network layer, and since I do not master its internals, I'd need some pre-review help to check that I haven't done horrible things.  If you have time, maybe you could precheck my fork for stupid mistakes?

**Comment by Sean-Der** [comment]
Hey @thomas-fossati, that is awesome! 

* Out of curiosity why did you choose to start hacking on this using `pions/dtls`?
* I would be more then happy to check out everything, if you do a rebase + `wip pr` I am happy to read through everything?
* Is there anything we can do to make this package better? Since you have read the code and poked around I am sure you saw some of my mistakes, anything I can do to make them better :)

Thanks!

**Comment by thomas-fossati** [comment]
Hi Sean,

> Hey @thomas-fossati, that is awesome!
> 
> * Out of curiosity why did you choose to start hacking on this using `pions/dtls`?

Mainly because it looked like a well architected piece of software which I could understand and modify without major heartburns :-)

> * I would be more then happy to check out everything, if you do a rebase + `wip pr` I am happy to read through everything?

Sounds good!  I'm going to have some time to do that at end of this week.

> * Is there anything we can do to make this package better? Since you have read the code and poked around I am sure you saw some of my mistakes, anything I can do to make them better :)

No particular comments for now, apart from "good work!".  I've only stumbled upon one [bug](https://github.com/thomas-fossati/dtls/commit/dbde4c64ba7e68a12ce5cc7649d8a29a08261f9d).
