### ISSUE TITLE
Why are most typed errors private?

### ISSUE THREAD

**Issue by GuiTeK** [pion/dtls#358]
Hi,

First, thank you for this library! It was really easy to get started with and works well!

The only issue I've encountered so far is that I can't know the reason of a `dtls.Conn.Read()` failure. Indeed, most typed errors are private: https://github.com/pion/dtls/blob/v2.0.8/errors.go#L16

So for example, I can't do:
```golang

if err == dtls.errBufferTooSmall { 
    // ...
} else if err == dtls.errDeadlineExceeded {
    // ...
}
```

Which is annoying because these are temporary/easily recoverable errors.

Is there any specific reason why these were made private? Could we change the first letter to an uppercase 👀 ?

**Comment by Sean-Der** [comment]
Hey @GuiTeK 

I think you can check `dtls.TemporaryError` we have them split up [here](https://github.com/pion/dtls/blob/master/errors.go#L23-L28) and I believe `errors.Is` should do the trick.

I am not against exporting the errors if it helps your work. Most of them are implementation specific, so if we refactor code it would be pretty hard to make sure we are consistently returning the same errrors.

**Comment by daenney** [comment]
I think a lot of these errors are internal because you're not really meant to recover from them. In most cases if you hit any error during a handshake the only sane thing to do is abort everything. There's probably a few that can be safely handled that way that are worth considering exporting, but I wouldn't want to go in and wholesale export all the errors.

**Comment by Sean-Der** [comment]
@daenney Agree.

I think what we have should work today. Users can distinguish between Fatal/Temporary errors, beyond that I think higher cost then value for exporting private stuff.
