### ISSUE TITLE
MessageClientKeyExchange decode logic can be improved

### ISSUE THREAD

**Issue by acevest** [pion/dtls#374]
https://github.com/pion/dtls/blob/fab1e7895e57316b850a8d0e86e2d5cae6594ee3/pkg/protocol/handshake/message_client_key_exchange.go#L50

maybe like this
```go
if publicKeyLength := int(data[0]); len(data) < publicKeyLength+1 {
```

**Comment by acevest** [comment]
and line 54
```go
m.PublicKey = append([]byte{}, data[1:]...)
```

should be 
```go
m.PublicKey = append([]byte{}, data[1:1+publicKeyLength]...)
```

?

**Comment by Sean-Der** [comment]
Hi @acevest 

IMO the following is better because it is explicit `if publicKeyLength := int(data[0]); len(data) != publicKeyLength+1 {` 

I do like `m.PublicKey = append([]byte{}, data[1:1+publicKeyLength]...)` since it is more explicit. I shouldn't change the behavior of the code, but could be nicer for readers.

I am going to close this issue since there is nothing actionable for the maintainers. I would really love for you to open the suggested PRs! thanks
