### ISSUE TITLE
Implement Null Cipher

### ISSUE THREAD

**Issue by digitalhurricane-io** [pion/dtls#40]
## Summary

Add ability to use null cipher

## Motivation

Reduce CPU usage

* [ ] write the codes
* [ ] write wiki

**Comment by jinleileiking** [comment]
After hours  for making null cipher about `sfu-ws`. I got these infos:

I use `--disable-webrtc-encryption` open chromium. The pion outputs `AVPF` question in sdp. After I change the sdp codes. Pion complaints ` no finger print`. It seems chromium do not generate fingerprint in no-encrypt mode.

I upload my temperate codes in jinleileiking-nullcipher branch of sdp and dtls.

**Comment by Sean-Der** [comment]
Hey @digitalhurricane-io 

Unfortunately it looks like we will never be able to do a `NULL` Cipher for WebRTC. The RFC states that encryption is mandatory. Did you open this ticket because you want to use DTLS outside of WebRTC?

If this is WebRTC we should probably not spend time implementing this. thanks!

**Comment by daenney** [comment]
Even if we could add a NULL cipher, I am strongly opposed to doing so.

Though with a NULL cipher we would still keep the authenticity and integrity pillars of TLS, the confidentiality one crumbles. Effectively, your payload is transmitted in the clear. This risks creating a scenario where people believe their transmissions are safe from prying eyes where in reality they are not, leading to a false sense of security. This is dangerous and the potential speedup of a NULL cipher is in my eyes not worth the massive foot-gun it represents and the potential undermining of trust in this library.

RFC 4785 classifies NULL-ciphers as authentication-only ciphers. OpenSSL does offer NULL ciphers but they are disabled by default and heavily warned against using due to the security risk they represent. 

AES-NI hardware acceleration was proposed and added to CPUs almost a decade ago and has been in major CPUs for at least half a decade. It's been available since Intel Westmere (2010), AMD Jaguar (2013) and ARMv8 (2011). Many embedded devices don't use x86 or ARMv8 but for that we have AES-CCM support available now, and PSK support, which makes encryption on low-power/embedded devices feasible.

Aside from the potential security holes the NULL cipher would be opening up, crypto/tls also does not support the NULL cipher and I think we should stay inline here with the crypto package of the Go standard library, as far as this is concerned. Other modern day implementations like rustls or ocaml-tls don't support NULL ciphers either. If anyone can convince the Go authors to accept NULL ciphers into crypto/tls I'd be more susceptible to having them in pion/dtls.

I'm going to close this issue but if other members feel this warrants further discussion please re-open it.

**Comment by Sean-Der** [comment]
@daenney I agree 100%! Thank you so much for the well written/multi-point response, that will make it really easy to not re-open this conversation.
