### ISSUE TITLE
client send 2 clienthello.

### ISSUE THREAD

**Issue by jinleileiking** [pion/dtls#49]
### Your environment.
  - Version: b4bc4798b938775e640c7d70d9c877c1096c24d0
  - Browser: chrome 71.0.3578.98
  - Other Information - use sfu-ws example

### What did you do?

click the publish button

### What did you expect?

There will be one client hello

### What happened?

There are 2 client hello in wireshark. Maybe the timer bug.

![Untitled](https://user-images.githubusercontent.com/93968/55394277-83a7fa00-5571-11e9-84c4-4582488fa25a.png)

**Comment by jinleileiking** [comment]
some log
```
dtls-package TRACE: 19:20:53.007194 client_handlers.go:202: flight1
dtls-package TRACE: 19:20:53.007248 client_handlers.go:205: flight3
(string) (len=44) "----------------send client hello-----------"
dtls-package TRACE: 19:20:53.017797 client_handlers.go:23: ServerHello
dtls-package TRACE: 19:20:53.017888 client_handlers.go:205: flight3
(string) (len=44) "----------------send client hello-----------"
```

**Comment by jinleileiking** [comment]
Any suggestion？

**Comment by maxhawkins** [comment]
Also seeing this on v1.3.3

**Comment by Sean-Der** [comment]
sending a `ClientHello` during `flight3` isn't an issue currently (@maxhawkins sending a malformed one is though)

* During `flight3` we send a `ClientHello` every second until the client has enough state to move onto `flight5`

* If the server sends a `handshakeTypeHelloVerifyRequest` we also should send a `ClientHello` but with a Cookie and increment the local SequenceNumber once.

---

@maxhawkins your issue is that the SequenceNumber was improperly incremented. The only time it should be 1 during a `flight3` is when we have a cookie. The possible bugs that could be happening here.

* Incorrectly assuming a packet is a `handshakeTypeHelloVerifyRequest`
* Incrementing the SequenceNumber used by `ClientHello` (a race or just bad logic)

**Comment by jinleileiking** [comment]
It seems not an issue. Closed for now
